server:
  port: 11000

spring:
  application:
    name: mall-ware
  datasource:
    url: jdbc:mysql://localhost:3306/mall_wms?characterEncoding=UTF-8
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  cloud:
    nacos:
      discovery:
        server-addr: 10.241.59.8:8848

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.cmc.mall.product.entity
  global-config:
    db-config:
      id-type: auto
logging:
  level:
    com.cmc.mall.ware: debug
